import{a as w,S as A,i as a}from"./assets/vendor-8-pyTk71.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const p of n.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&i(p)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const E="https://pixabay.com/api/",S="52282020-0fa7caca98833a1caa1732196";function y(e,r=1){const o={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:20};return w.get(E,{params:o}).then(i=>i.data)}const h=document.querySelector(".gallery"),c=document.querySelector(".loader"),u=document.querySelector(".loader-text"),_=new A(".gallery a",{captionsData:"alt",captionDelay:250});function m(e){if(!Array.isArray(e)||e.length===0)return;const r=e.map(o=>`
<li class="gallery__item">
  <a class="gallery__link" href="${o.largeImageURL}">
    <img class="gallery__image" src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${o.likes}</span></p>
    <p class="info-item"><b>Views</b><span>${o.views}</span></p>
    <p class="info-item"><b>Comments</b><span>${o.comments}</span></p>
    <p class="info-item"><b>Downloads</b><span>${o.downloads}</span></p>
  </div>
</li>`).join("");h.insertAdjacentHTML("beforeend",r),_.refresh()}function q(){h.innerHTML=""}function g(){c&&(c.style.display="flex"),u&&(u.style.display="block")}function f(){c&&(c.style.display="none"),u&&(u.style.display="none")}const s=document.querySelector(".load-more");function b(){s&&(s.style.display="block")}function L(){s&&(s.style.display="none")}function v(){return s}const x=document.querySelector(".form");let l="",d=1;const M=v();x.addEventListener("submit",e=>{if(e.preventDefault(),l=e.target["search-text"].value.trim(),!l){a.warning({title:"Warning",message:"Please enter a search query."});return}d=1,q(),L(),g(),y(l,d).then(r=>{if(f(),!r||!Array.isArray(r.hits)||r.hits.length===0){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}m(r.hits),r.hits.length===20&&b()}).catch(r=>{f(),a.error({title:"Error",message:"An error occurred while fetching images."}),console.error(r)})});M.addEventListener("click",()=>{d+=1,g(),L(),y(l,d).then(e=>{f(),e.hits.length&&(m(e.hits),e.hits.length===20&&b())}).catch(e=>{f(),a.error({title:"Error",message:"An error occurred while fetching more images."}),console.error(e)})});
//# sourceMappingURL=index.js.map
